<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Retry_geetest_wait</name>
   <tag></tag>
   <elementGuidId>b3b3bfc1-6d94-421f-9f7c-35fb9cb93541</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.geetest_wait</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='captcha-box']/div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.geetest_wait</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>69534c97-e703-4924-adbb-c14a2ba7dfe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>geetest_wait</value>
      <webElementGuid>75e36ed2-5f44-434c-9075-6e5ee8e683d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;captcha-box&quot;)/div[@class=&quot;geetest_holder geetest_wind geetest_wait_compute&quot;]/div[@class=&quot;geetest_wait&quot;]</value>
      <webElementGuid>ad22b2a3-0e63-4a8f-a74b-a2cf8b4f6db6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Bukalapak/Register/iframe_Request unsuccessful. Incapsula inci_d47fd5</value>
      <webElementGuid>6885fb27-c255-429c-982b-b8dd50abea54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='captcha-box']/div/div[3]</value>
      <webElementGuid>496e835d-ec74-46fc-8a26-328f206a03a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Retry'])[1]/following::div[14]</value>
      <webElementGuid>c80a3edd-e720-4a90-94fa-bab7e2f415a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click to verify'])[1]/following::div[14]</value>
      <webElementGuid>259a013c-6bde-4faa-88bf-5262ccf22344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[3]</value>
      <webElementGuid>7b4b2b72-4ee2-429c-b57d-3324ac069e66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
