<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login_bl-code-input-2</name>
   <tag></tag>
   <elementGuidId>19154290-98bd-4ca3-bfc0-5ca10a7806e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bl-code-input-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bl-code-input-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#bl-code-input-2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c6fc5ed2-f33f-4336-bb06-d3636d4647b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>52431a42-2113-4791-9b6d-06e04ac64678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cf78beab-9734-4034-8e40-544559979e59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bl-code-input-2</value>
      <webElementGuid>d4629be4-ac08-4dcb-ada9-0cad4df63862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>42548aac-78f2-45fe-92ea-40fc41edd2e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bl-text-field__input</value>
      <webElementGuid>8a1a5087-f490-4bcd-b981-0e3c226ffb63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bl-code-input-2&quot;)</value>
      <webElementGuid>b42249a1-54e0-4778-b3a0-4bac733568a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bl-code-input-2']</value>
      <webElementGuid>aa574091-7598-49e8-9d13-b0ee22bea87c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TFAJS-1725522802747']/section/div/div[2]/div/div[2]/div/div/div/div/div/div[2]/div[3]/div/div/input</value>
      <webElementGuid>584b6dff-df54-4b1e-813b-b1043427c10e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>5f1d2426-7d9a-4621-8aaa-e30654a791ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'bl-code-input-2']</value>
      <webElementGuid>ded0666c-24f1-4e7b-8dbc-aac0847c030a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
