<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login_bl-code-input-1</name>
   <tag></tag>
   <elementGuidId>69fc7446-4a2d-4be1-8973-8495e32d2e4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bl-code-input-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bl-code-input-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#bl-code-input-1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>773c6d65-5bdc-46dd-b27e-490e3d30c17a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>290ac7e1-70ac-47f2-b85d-18784c3de837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1802c3b2-5cdc-465c-b81a-6d5e27ece34a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bl-code-input-1</value>
      <webElementGuid>d58f18b1-1aa3-4a49-8303-6ce4eed74ff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>f836d1c2-fe8f-4395-a31b-5852cf4296e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bl-text-field__input</value>
      <webElementGuid>430ed233-7837-44b3-bf1f-c0c735a9e5ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bl-code-input-1&quot;)</value>
      <webElementGuid>8cc2dccd-12d4-4f34-834b-06640ab2616c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bl-code-input-1']</value>
      <webElementGuid>f403e024-77e2-42af-81d4-fb761d4ddce4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TFAJS-1725522802747']/section/div/div[2]/div/div[2]/div/div/div/div/div/div[2]/div[2]/div/div/input</value>
      <webElementGuid>1cb9bfdd-d777-4202-819b-155381a831cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>2ac0f50c-811c-48d6-8f41-432bacb48d40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'bl-code-input-1']</value>
      <webElementGuid>1c3da2b4-d89b-484b-9a3e-331a83ad4e34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
