<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login_bl-code-input-4</name>
   <tag></tag>
   <elementGuidId>e8ae9cbf-f056-4fc7-9ba2-c1f52cdd92d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bl-code-input-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bl-code-input-4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#bl-code-input-4</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3616aaa5-c6f0-4e54-880b-b3747bdf0880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>691c0475-0e88-46ba-a70b-6189bfe017e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e73c55b8-6d29-47c6-9981-1187d3c0b326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bl-code-input-4</value>
      <webElementGuid>2eed061d-d68f-465c-b65a-375402794444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>05357ff5-4ca9-44a8-afdd-abfefc2f7ea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bl-text-field__input</value>
      <webElementGuid>f225cc1c-085d-4d5a-b614-45f07373c52d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bl-code-input-4&quot;)</value>
      <webElementGuid>414cd047-f33e-4b2f-adbf-9c88244fe2d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bl-code-input-4']</value>
      <webElementGuid>8b966b26-76ab-48c6-a4cb-a2a767a4ba5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TFAJS-1725522802747']/section/div/div[2]/div/div[2]/div/div/div/div/div/div[2]/div[5]/div/div/input</value>
      <webElementGuid>dc427f05-60cd-4c15-add8-99070bb237e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input</value>
      <webElementGuid>abe0eefa-6499-4d1a-b4b6-c963dfd3cabc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'bl-code-input-4']</value>
      <webElementGuid>b0c30834-80da-4bd6-a07b-88f5e5ad271d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
