<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login_bl-code-input-3</name>
   <tag></tag>
   <elementGuidId>26c0a741-8da5-43dc-b45e-07d9335d26eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bl-code-input-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bl-code-input-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#bl-code-input-3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>822c3009-742b-49d3-892c-348b4c0aaf3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3a5d831c-40f0-41be-a63d-e216de26bb8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>172026e4-f99d-4829-92cf-ff6c0647b074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bl-code-input-3</value>
      <webElementGuid>673e30f3-b002-4a72-bf63-ce7594ffe93c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>e9182dc1-f825-4a2c-9dea-e934f68256b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bl-text-field__input</value>
      <webElementGuid>1e9cc988-39f7-422c-be57-49c0cbbb6452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bl-code-input-3&quot;)</value>
      <webElementGuid>e0595b7e-160e-4a83-9eaf-f44026086e87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bl-code-input-3']</value>
      <webElementGuid>a2d7cbc1-dfef-47f3-b2a3-bf6235e75e50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TFAJS-1725522802747']/section/div/div[2]/div/div[2]/div/div/div/div/div/div[2]/div[4]/div/div/input</value>
      <webElementGuid>26d946af-b39c-4a5e-b19e-2e9bb116004b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>2ed52cef-973e-487d-ad38-8d64e2602ea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'bl-code-input-3']</value>
      <webElementGuid>3786d142-fba0-4500-b746-a7ab157c48f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
