<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>alamat_title</name>
   <tag></tag>
   <elementGuidId>b19d0476-03ef-414f-8cdb-1874ddb3fb79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.c-fld__error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
