<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_To navigate, press the arrow keys_js-maps-search</name>
   <tag></tag>
   <elementGuidId>b2f2794a-d37e-4b82-b134-9a2fe4c1caad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='js-maps-search']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#js-maps-search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Cari Lokasi&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>31b4c06b-70f9-4514-a3cc-1e31ed393941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>js-maps-search</value>
      <webElementGuid>405bb710-1fd8-45e9-8d5e-9704e30585e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari Lokasi</value>
      <webElementGuid>c2019bcf-ea23-446c-b888-0f3ed030fe91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>138a75da-5737-41bd-aeb7-47a79648dc63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-maps__search maps-input controls</value>
      <webElementGuid>1a454c61-e3b9-4984-8c86-d0e2339f4809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-maps-search&quot;)</value>
      <webElementGuid>5d4cccb4-279d-4daf-af0d-7500f648cfec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='js-maps-search']</value>
      <webElementGuid>3535fdc6-728e-4462-909a-ecb3b1074e0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='js-maps']/div/div[3]/div[3]/input</value>
      <webElementGuid>e1d4be5f-9a25-471f-b643-4fca31bd4a4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>cab5c3f6-1482-4f55-b568-412f90da5705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'js-maps-search' and @placeholder = 'Cari Lokasi' and @type = 'text']</value>
      <webElementGuid>2d56ef0a-3f49-4ffd-925c-21d2e23026c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
