<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Penerima_name</name>
   <tag></tag>
   <elementGuidId>c7d57a86-2ae2-4fe0-aa13-c1fecd410fa7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Isi Nama Lengkap&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>006f3537-b06c-437c-8850-df73be3378e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9ae26883-39e8-4b23-8b06-9fa70651f440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>6c31e637-16a6-4e26-b460-1bc64453ce71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Isi Nama Lengkap</value>
      <webElementGuid>8d0e5e09-7c55-451d-be3c-6577a8f8eb7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-vv-rules</name>
      <type>Main</type>
      <value>required|max:100</value>
      <webElementGuid>b02d6bab-a3a4-4e3f-a666-fb62329ced7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-vv-as</name>
      <type>Main</type>
      <value>Nama Penerima</value>
      <webElementGuid>28d84d60-1e90-4590-80a8-5c9afec65df8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-inp</value>
      <webElementGuid>3313330e-3e2c-4e77-88aa-491ffb0f08c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-vv-id</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>c8f1ee01-e411-4d7a-8999-f82df3985b6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a7203cdf-9f18-458c-ae13-e18aaa93b22a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9f002d0b-010e-48e1-a750-a5a36f9c9fc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vm-user-addresses&quot;)/div[2]/div[2]/div[2]/div[@class=&quot;c-remodal c-remodal--medium&quot;]/div[@class=&quot;c-remodal__wrapper&quot;]/div[@class=&quot;c-remodal__content&quot;]/div[@class=&quot;c-remodal__panel&quot;]/div[@class=&quot;c-remodal__panel__body&quot;]/div[1]/div[1]/div[@class=&quot;c-tab c-tab--inside&quot;]/div[@class=&quot;c-tab__content is-active&quot;]/div[@class=&quot;c-tab__content__body&quot;]/div[1]/form[1]/div[@class=&quot;c-modal__content&quot;]/div[@class=&quot;c-fld c-fld--split&quot;]/div[@class=&quot;c-fld__col&quot;]/input[@class=&quot;c-inp&quot;]</value>
      <webElementGuid>2282c155-fe4c-4ed2-8c17-a804930870b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='name']</value>
      <webElementGuid>408b4d89-1b24-41cb-b4e3-18e81bce0eb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vm-user-addresses']/div[2]/div[2]/div[2]/div/div/div/div/div[2]/div/div/div/div/div/div/form/div/div[2]/div[2]/input</value>
      <webElementGuid>fccbb6c1-a5ee-486c-81ef-997912770ca8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>b520c9e8-89f6-456a-813f-b4f37db6aca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'name' and @placeholder = 'Isi Nama Lengkap']</value>
      <webElementGuid>35776d56-dfcf-4a7d-8b22-331e45bb6a5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
