<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Alamat Sebagai_title</name>
   <tag></tag>
   <elementGuidId>138a5a3d-a1bd-4538-8eb6-b6824a261e38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;title&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Contoh: Kantor, Kos, Rumah, dll&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb35cf9e-05ea-41e8-b0c5-1867af43a84b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>81515ff9-e1d7-4b4d-a83c-6249a608ffc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>caff7ab2-4bd0-485b-92e6-353f48f24e46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contoh: Kantor, Kos, Rumah, dll</value>
      <webElementGuid>aaf2f596-eb68-4bb9-81e6-f88702e3bc3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-vv-rules</name>
      <type>Main</type>
      <value>required|max:100</value>
      <webElementGuid>0c76cdbe-2a8c-4e53-962f-2b8dd0719aac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-vv-as</name>
      <type>Main</type>
      <value>Nama Alamat</value>
      <webElementGuid>471871f4-cc08-403b-9518-cff927a40ddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-inp</value>
      <webElementGuid>9e70348e-d634-44e8-8666-c3efb0a53840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-vv-id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6721f0a2-de60-4ef3-8794-5639fb88aa77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>37a82a81-0ee7-4424-be5c-2fdd1d200ac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>87b9173d-df9d-40bb-a332-e9766dab74c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vm-user-addresses&quot;)/div[2]/div[2]/div[2]/div[@class=&quot;c-remodal c-remodal--medium&quot;]/div[@class=&quot;c-remodal__wrapper&quot;]/div[@class=&quot;c-remodal__content&quot;]/div[@class=&quot;c-remodal__panel&quot;]/div[@class=&quot;c-remodal__panel__body&quot;]/div[1]/div[1]/div[@class=&quot;c-tab c-tab--inside&quot;]/div[@class=&quot;c-tab__content is-active&quot;]/div[@class=&quot;c-tab__content__body&quot;]/div[1]/form[1]/div[@class=&quot;c-modal__content&quot;]/div[@class=&quot;c-fld c-fld--split&quot;]/div[@class=&quot;c-fld__col&quot;]/input[@class=&quot;c-inp&quot;]</value>
      <webElementGuid>2fe872f7-e2a8-4574-876d-038cdc1b869f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='title']</value>
      <webElementGuid>cb5bd7b5-638a-4554-b5dc-cc53e5375de2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vm-user-addresses']/div[2]/div[2]/div[2]/div/div/div/div/div[2]/div/div/div/div/div/div/form/div/div/div[2]/input</value>
      <webElementGuid>46eda983-40d0-43f1-94ae-a989f634ac91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>4ec9aad1-6fb7-4a87-95a0-107ff50ad43c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'title' and @placeholder = 'Contoh: Kantor, Kos, Rumah, dll']</value>
      <webElementGuid>7c2ee5bc-3a32-4ab1-9a96-6ff36685c72b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
