<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No. Telepon_phone</name>
   <tag></tag>
   <elementGuidId>9d689045-48f1-4ea0-9419-c66bacc5f020</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='phone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;phone&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;phone&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f4939b83-b92c-4163-9d01-a802b3c44bec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9d22a1e4-d0ea-464b-af3a-49c82fd57449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>96c0e11d-84f5-405f-a1c6-6e3930a711d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-vv-rules</name>
      <type>Main</type>
      <value>required|phone</value>
      <webElementGuid>01d5ac6c-eedf-4f0d-ae29-7e289e1e7537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-vv-as</name>
      <type>Main</type>
      <value>Nomor Telepon</value>
      <webElementGuid>d29e83cb-21b9-41e2-b31b-b7942b46ff13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-inp</value>
      <webElementGuid>20909782-ec76-4d72-8b68-384a4853c046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-vv-id</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>c78c8d25-866d-429b-a098-49f8c4612a6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>aeb2535c-5676-42f1-83ef-3abb442a11bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>15606cc7-6254-4f0a-a660-5e25fd92c2d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vm-user-addresses&quot;)/div[2]/div[2]/div[2]/div[@class=&quot;c-remodal c-remodal--medium&quot;]/div[@class=&quot;c-remodal__wrapper&quot;]/div[@class=&quot;c-remodal__content&quot;]/div[@class=&quot;c-remodal__panel&quot;]/div[@class=&quot;c-remodal__panel__body&quot;]/div[1]/div[1]/div[@class=&quot;c-tab c-tab--inside&quot;]/div[@class=&quot;c-tab__content is-active&quot;]/div[@class=&quot;c-tab__content__body&quot;]/div[1]/form[1]/div[@class=&quot;c-modal__content&quot;]/div[@class=&quot;c-fld c-fld--split&quot;]/div[@class=&quot;c-fld__col&quot;]/input[@class=&quot;c-inp&quot;]</value>
      <webElementGuid>466d72df-9eca-4295-9547-5c0201d6c091</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='phone']</value>
      <webElementGuid>017906f9-a413-4a78-94ff-026d4f6ea29b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vm-user-addresses']/div[2]/div[2]/div[2]/div/div/div/div/div[2]/div/div/div/div/div/div/form/div/div[3]/div[2]/input</value>
      <webElementGuid>5a26c1fc-658e-4d7b-a7c7-f8d3e8749d01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>078ee6a9-8adf-41ef-b8d8-39ac1ebe5bc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'phone']</value>
      <webElementGuid>b0727ca2-699c-4b78-88a5-19b1a8d78fe2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
