<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Asuransi_bl-thumbnail--img</name>
   <tag></tag>
   <elementGuidId>f02b3158-ef7f-4cd0-a9f3-047d12c6f3a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='product-explorer-container']/div/div/div[2]/div/div[2]/div[3]/div/div/div/div/div/figure/div/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.bl-thumbnail--img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;LIGE 2021 terbaru jam tangan pria fashion tahan air baja tahan karat olahraga kronograf jam tangan&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1c052f83-e637-4156-bee8-def43d421105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>LIGE 2021 terbaru jam tangan pria fashion tahan air baja tahan karat olahraga kronograf jam tangan</value>
      <webElementGuid>9344c542-b7c5-4529-bed9-056006b90c6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://s0.bukalapak.com/img/00076797592/s-330-330/data.jpeg.webp</value>
      <webElementGuid>bb2704a3-1a66-4476-af88-d3db2ff8a2c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bl-thumbnail--img</value>
      <webElementGuid>f37557cc-1d21-4295-9d44-fce14866cc71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-explorer-container&quot;)/div[@class=&quot;bl-container&quot;]/div[@class=&quot;bl-flex-container&quot;]/div[@class=&quot;bl-flex-item bl-product-list-wrapper&quot;]/div[@class=&quot;bl-flex-container direction-column&quot;]/div[2]/div[3]/div[@class=&quot;bl-flex-container flex-wrap is-gutter-16&quot;]/div[@class=&quot;bl-flex-item mb-8&quot;]/div[@class=&quot;te-product-card bl-product-card-new&quot;]/div[@class=&quot;bl-product-card-new__wrapper&quot;]/div[@class=&quot;bl-product-card-new__thumbnail&quot;]/figure[@class=&quot;bl-thumbnail&quot;]/div[@class=&quot;bl-thumbnail__slider bl-thumbnail__slider--bottom bl-thumbnail__slider--light&quot;]/div[1]/a[@class=&quot;slide&quot;]/img[@class=&quot;bl-thumbnail--img&quot;]</value>
      <webElementGuid>b6294392-dd47-4a7f-8447-7d9ced84d2ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='product-explorer-container']/div/div/div[2]/div/div[2]/div[3]/div/div/div/div/div/figure/div/div/a/img</value>
      <webElementGuid>8ab6fc43-5bb0-4937-b5b3-0bb7b560c8a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='LIGE 2021 terbaru jam tangan pria fashion tahan air baja tahan karat olahraga kronograf jam tangan']</value>
      <webElementGuid>6522252b-bb59-4ca9-b753-c0cb58145fef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//figure/div/div/a/img</value>
      <webElementGuid>09f98c54-3639-48a2-97b2-30c094469528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'LIGE 2021 terbaru jam tangan pria fashion tahan air baja tahan karat olahraga kronograf jam tangan' and @src = 'https://s0.bukalapak.com/img/00076797592/s-330-330/data.jpeg.webp']</value>
      <webElementGuid>70b0a1d0-f9dd-4a16-8600-2dc234cbbdda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
