<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pembayaran_payment-category</name>
   <tag></tag>
   <elementGuidId>a5164638-7447-4ba2-a761-d173b4b51f04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dana']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dana</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;DANA&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8f9cd3d1-6c5d-4c0c-b6f3-ad3902d11dde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>e2b4a881-18cd-4595-a360-1cbf9c698b95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payment-category</value>
      <webElementGuid>82be9fa2-aa68-45cf-8971-668b83b27ee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dana</value>
      <webElementGuid>80a67639-35b4-4a0d-9ffc-cfa81332c7fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bl-radio-button__input</value>
      <webElementGuid>e473bfcf-7113-49b2-8d76-e2e1373a911b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>dana</value>
      <webElementGuid>c51e0f82-e1f5-40d5-8839-e2139a44a3d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-checkout-container&quot;)/fragment-loader[1]/div[@class=&quot;tuku&quot;]/div[1]/section[1]/div[1]/div[@class=&quot;mb-20 bl-card bl-card--outlined&quot;]/div[2]/div[@class=&quot;bl-payment-category&quot;]/label[@class=&quot;bl-payment-category__label&quot;]/div[@class=&quot;bl-flex-container p-20 pb-16&quot;]/div[@class=&quot;bl-flex-item&quot;]/label[@class=&quot;bl-radio-button&quot;]/input[@id=&quot;dana&quot;]</value>
      <webElementGuid>e5816413-7d3a-428e-8684-5f25484c0b11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dana']</value>
      <webElementGuid>65ffc876-e07b-4f46-82e7-34815308d500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-checkout-container']/fragment-loader/div/div/section/div/div/div[2]/div[2]/label/div/div/label/input</value>
      <webElementGuid>cc63529e-3e00-43db-9ba0-7cad35b473f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>85a0ee5a-6e13-4667-a635-dd08fedc0f1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'payment-category' and @id = 'dana']</value>
      <webElementGuid>4768135c-b740-4c79-9498-97420832c059</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
