<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_checkbox</name>
   <tag></tag>
   <elementGuidId>f2d45315-e9db-462b-9112-24617b2e44f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='seller_92203090']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.bl-checkbox.mr-16 > input[type=&quot;checkbox&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;&quot;s >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8200f738-978f-4eb0-9a81-c194414f99bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>95e8c4bc-f299-44f4-ae6d-15fe7b029229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>seller_92203090</value>
      <webElementGuid>121965be-3533-4d96-bbbb-10be438e02f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-cart-wrapper&quot;)/section[@class=&quot;bl-section&quot;]/div[@class=&quot;bl-container&quot;]/div[@class=&quot;bl-flex-container justify-center is-gutter-24&quot;]/div[@class=&quot;bl-flex-item is-col-8&quot;]/div[@class=&quot;bl-card bl-card--outlined&quot;]/div[@class=&quot;mb-0 qa-cart-seller&quot;]/div[@class=&quot;p-20 pb-12 u-border-bottom&quot;]/div[@class=&quot;bl-flex-container&quot;]/div[@class=&quot;bl-flex-item&quot;]/label[@class=&quot;bl-checkbox mr-16&quot;]/input[1]</value>
      <webElementGuid>402cc718-4a4b-4d14-8d67-3268a72fcd50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='seller_92203090']</value>
      <webElementGuid>b6f01ff6-2ae0-4406-8a16-0a6b8a5ce9a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='js-cart-wrapper']/section[2]/div/div/div/div[2]/div/div/div/div/label/input</value>
      <webElementGuid>0ff1f931-2102-495a-83db-6038fbf509e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/label/input</value>
      <webElementGuid>49c82b63-1fbc-4424-8573-80479ec9a767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>6d4869a1-df31-4856-97f0-de4cf4d96f55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
